name: example_package_with_js
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  flutter: ">=3.16.0"
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_package.js
    - lib/app_package.js
